### ISSUE TITLE
LinkedIn default label

### ISSUE THREAD

**Issue by jamesmacwhite** [presseddigital/linkit#62]
Hi @samhibberd 

Something minor, but the default label for the LinkedIn settings model currently is `Linked In`. For stylistic and branding purposes, the value should probably be `LinkedIn`.

https://github.com/fruitstudios/craft-linkit/blob/master/src/models/LinkedIn.php#L27

Of course, this can be overridden to anything for any new/existing linkit field, but as a default it probably makes more sense to be `LinkedIn`.

**Comment by jamesmacwhite** [comment]
https://github.com/presseddigital/linkit/pull/94

**Comment by samhibberd** [comment]
Added with latest releases:

Craft 4: https://github.com/presseddigital/linkit/releases/tag/4.0.0
Craft 3: https://github.com/presseddigital/linkit/releases/tag/3.0.0
