### ISSUE TITLE
Better configuration support for Craft GraphQL

### ISSUE THREAD

**Issue by warrebuysse** [presseddigital/linkit#69]
Currently, linkIt returns a preformatted string in the GraphQL interface. What is expected is an object, like the following: 
```
link: {
 title: "Some label",
 uri: "some-uri-without/base-url,
 target: "_blank",
 formatted: "<a href="...">Some label</a>",
 // anything else
}
```

**Comment by tekstrand** [comment]
We're running into this as well. Would be great to see. We haven't decided how to tackle it quite yet, whether we'll write something on the backend or frontend. We've also considered spending some time opening a PR to this repo.

**Comment by clieee** [comment]
Any updates on this?

**Comment by tekstrand** [comment]
We ended up handling this on the frontend.

```
/**
 * This will take a html tag (should be from a GraphQL Query) and will return an object with all the properties that it has.
 */

function createElementFromHTML(htmlString) {
  var div = document.createElement('div');
  div.innerHTML = htmlString.trim();

  return div.firstChild;
}

function desconstructHTML(linkitField) {
  let htmlElement = createElementFromHTML(linkitField);
  let attributesNames = htmlElement.getAttributeNames();
  let linkitFieldTransformed = new Object();
  attributesNames.forEach((element) => (linkitFieldTransformed[element] = htmlElement.getAttribute(element)));
  linkitFieldTransformed['title'] = htmlElement.title;
}

export default desconstructHTML;
```

**Comment by peaffenzeller** [comment]
having the same issue here.
any updates?

**Comment by tekstrand** [comment]
We ran into more issues here, and ended up creating a custom field type that extends LinkIt in order to support GQL.

**Comment by sjcallender** [comment]
It's impossible to get the Title of a linked Entry via the current GraphQL configuration.

**Comment by samhibberd** [comment]
Added with latest releases:

Craft 4: https://github.com/presseddigital/linkit/releases/tag/4.0.0
Craft 3: https://github.com/presseddigital/linkit/releases/tag/3.0.0
