### ISSUE TITLE
Target is outputting "1" instead of "_blank"

### ISSUE THREAD

**Issue by darylknight** [presseddigital/linkit#71]
I just noticed on a site I'm working on, that if a LinkIt field has "Open link in new tab" checked, it's outputting "1" instead of "_blank" in the code. Still seems to work, but it's not valid:

`{% if block.button|length %}<a href="{{ block.button.url }}" class="btn btn-red mt-2" target="{{ block.button.target }}">{{ block.button.text }}</a>{% endif %}`

![image](https://user-images.githubusercontent.com/1250017/68024238-2c5a3b80-fcb2-11e9-8039-8a2444c207ef.png)

![image](https://user-images.githubusercontent.com/1250017/68024167-fa48d980-fcb1-11e9-9ebc-9c22d425d0d6.png)

**Comment by simonkuran** [comment]
I'm guessing this is intended. I write my conditionals like a boolean check `{% if block.button.target %} target="_blank"{% endif %}`.

**Comment by jamesmacwhite** [comment]
@simonkuran In Craft 3 Linkit now has a `.targetString` property, which gives you the actual value for the target attribute, so it's a bit cleaner.

**Comment by samhibberd** [comment]
@jamesmacwhite is right on this, the target string property covers off this.
