### ISSUE TITLE
clean up phone numbers for tel:links

### ISSUE THREAD

**Issue by ursbraem** [presseddigital/linkit#74]
The format for phone numbers is different for humans or for `tel:` links.
Humans use whitespace, which won't work in a tel. link.

Would you like a pull request?

**Comment by samhibberd** [comment]
Added with latest releases:

Craft 4: https://github.com/presseddigital/linkit/releases/tag/4.0.0
Craft 3: https://github.com/presseddigital/linkit/releases/tag/3.0.0
